import LegalPage from '@/src/components/legal/LegalPage';
export const metadata = { title: 'Condizioni del servizio meteo | Emme-Effe Services', alternates: { canonical: '/termini-meteo' } };
export default function WeatherTermsPage() {
  return <LegalPage title="Condizioni del servizio meteo e di consulenza">
    <p>Versione 2026-10-03-v3. Queste condizioni disciplinano l’area clienti meteo e le prestazioni consulenziali di Emme-Effe Services di Lorenzo Mercurio Fedel, Via dello Stadio 7, 38042 Baselga di Piné (TN), P. IVA 02833120229. Contatto operativo: elaborazione@emmeeffeservices.it. Non riguardano gli altri servizi aziendali.</p>
    <h2>1. Oggetto della prestazione</h2><p>Il servizio è una prestazione consulenziale libero professionale relativa alla scelta e all’installazione informatica della stazione meteorologica, alla configurazione della trasmissione, raccolta, visualizzazione e gestione dei dati. Le attività incluse, gli eventuali interventi sul posto e i risultati da consegnare sono definiti nel preventivo. La fornitura di hardware, opere edili o elettriche, certificazioni, manutenzione e assistenza continuativa non sono incluse salvo accordo espresso; gli interventi riservati a soggetti abilitati sono affidati a tali soggetti. I dati meteo non sostituiscono bollettini ufficiali né servizi di allerta o certificazioni meteorologiche.</p>
    <h2>2. Registrazione e incarico</h2><p>La registrazione gratuita permette la gestione del profilo e l’invio di richieste di consulenza. Non costituisce ordine, acquisto né assegnazione automatica di stazioni. L’incarico nasce con l’accettazione del preventivo su supporto durevole, che specifica ambito, prezzo totale e imposte applicabili, spese, tempi, modalità di pagamento, eventuali servizi ricorrenti e configurazione dei dati. Non si addebitano prestazioni ulteriori senza accordo. Le condizioni specifiche del preventivo prevalgono su quelle generali compatibilmente con le norme inderogabili.</p>
    <h2>3. Collaborazione e accessi</h2><p>Il cliente fornisce dati tecnici corretti, disponibilità di alimentazione e connettività, autorizzazioni necessarie e accessi tecnici concordati, preferibilmente dedicati e revocabili. Non inviare password tramite richieste o email: il trasferimento di credenziali avviene con modalità sicure concordate. Gli accessi sono utilizzati solo per l’incarico. Eventuali modifiche ai dati tecnici inseriti in fase di consulenza sono richieste indicando nome e ID della stazione.</p>
    <h2>4. Gestione primaria e copia dei dati</h2><p>La gestione primaria può risiedere sul sito e sui sistemi del cliente. Una copia speculare può essere inviata ai database di emme-effe meteo soltanto secondo la configurazione concordata, indicando quali dati, per quali finalità e con quale conservazione. La copia non costituisce un backup garantito né comporta il trasferimento di diritti sui dati; diritti di utilizzo, pubblicazione ed eventuale esportazione sono definiti nell’incarico. Nessun trasferimento di dati ulteriori rispetto a quelli concordati è autorizzato da queste condizioni.</p>
    <h2>5. Opzione di rotazione a 25 ore</h2><p>In alternativa alla conservazione storica della copia su emme-effe meteo, è possibile concordare una finestra mobile di 25 ore: 24 ore necessarie ai grafici giornalieri più un’ora di margine. Questa opzione deve essere richiesta e attivata tecnicamente per la stazione; la registrazione o l’accettazione delle presenti condizioni non la attiva automaticamente. I campioni più vecchi della finestra sono rimossi con una procedura periodica la cui frequenza viene indicata nell’incarico. Archivi storici, aggregati e copie di backup sono esclusi dalla conservazione ordinaria della copia se non espressamente concordati; eventuali tempi di rotazione dei backup sono documentati separatamente. L’archivio primario del cliente resta soggetto alla sua configurazione. I dati eliminati dalla copia non sono recuperabili dal servizio e le funzioni che richiedono uno storico più lungo possono non essere disponibili.</p>
    <h2>6. Pubblicazione e riservatezza</h2><p>La pubblicazione di stazione, ubicazione e dati sul portale è concordata con il cliente. Il profilo associato può mostrare nome, progetto e logo; il cliente deve avere titolo per i contenuti forniti. La casella di indicizzazione del profilo riguarda i motori di ricerca e non rende privata la pagina. La disattivazione di una stazione ne impedisce la visualizzazione nelle pagine pubbliche del sito, senza cancellare automaticamente i dati conservati. Per dati personali si applica la Privacy Policy; quando il professionista tratta dati per conto del cliente, ruoli, istruzioni e misure sono disciplinati dall’accordo previsto dall’art. 28 GDPR ove necessario.</p>
    <h2>7. Tempi, assistenza e responsabilità</h2><p>Tempi e dipendenze sono stabiliti nel preventivo; ritardi dovuti a indisponibilità del cliente, hardware, connessione o fornitori sono comunicati e gestiti concordando il prosieguo. L’attività è svolta con la diligenza professionale richiesta; precisione dei sensori e disponibilità delle reti dipendono anche da fattori esterni. Non è promesso un servizio ininterrotto o un livello di disponibilità salvo specifico accordo. Nessuna clausola esclude responsabilità per dolo, colpa grave o altre responsabilità inderogabili, né limita i diritti riconosciuti ai consumatori.</p>
    <h2>8. Recesso del consumatore</h2><p>Per contratti a distanza o fuori dei locali commerciali, il consumatore beneficia del diritto di recesso previsto dagli artt. 52 e seguenti del Codice del consumo, normalmente entro 14 giorni dalla conclusione, salvo termini maggiori previsti dalla legge. Può esercitarlo con una dichiarazione inequivoca inviata a elaborazione@emmeeffeservices.it o alla sede, indicando nome, incarico e volontà di recedere. Esempio: “Comunico il recesso dall’incarico concordato il [data], intestato a [nome e recapito]”. Il rimborso e gli eventuali costi proporzionali seguono gli artt. 56–57. L’avvio durante il termine di recesso richiede una richiesta espressa separata del consumatore; per perdere il diritto dopo la completa esecuzione occorrono i presupposti dell’art. 59. L’accettazione delle condizioni in fase di registrazione non costituisce tale richiesta né rinuncia al recesso.</p>
    <h2>9. Chiusura del rapporto e cancellazione account</h2><p>Per richiedere la chiusura dell’account scrivi a elaborazione@emmeeffeservices.it dall’indirizzo associato, indicando il nome e, se utile, gli ID delle stazioni. Non inviare la password. La richiesta viene gestita previa verifica proporzionata dell’identità, senza automatismi. La cancellazione dell’account è distinta da recesso, conclusione o disdetta di un incarico e non annulla corrispettivi già dovuti. I diritti sui dati personali restano esercitabili anche tramite i contatti della Privacy Policy, senza formalità obbligatorie: risposta di norma entro un mese e conservazione solo nei casi e per i tempi consentiti dalla legge. La cessazione di trasmissione, esportazione e rimozione delle copie meteo viene concordata nel rispetto dell’incarico e dei diritti applicabili.</p>
    <h2>10. Reclami, legge e modifiche</h2><p>Per segnalazioni o contestazioni contatta elaborazione@emmeeffeservices.it, indicando il servizio interessato. Si applica la legge italiana, fatti salvi i diritti inderogabili e le tutele applicabili al consumatore, incluso il foro del suo luogo di residenza o domicilio quando previsto. Le modifiche future sono pubblicate con nuova versione e non alterano retroattivamente gli incarichi già accettati senza accordo. Queste condizioni completano l’incarico senza sostituire preventivo, informativa privacy o accordi sul trattamento dei dati.</p>
  </LegalPage>;
}
