import LegalPage from '@/src/components/legal/LegalPage';
export const metadata = { title: 'Privacy Policy | Emme-Effe Services', alternates: { canonical: '/privacy' } };
export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy">
    <h2>1. Titolare e ambito</h2><p>Emme-Effe Services di Lorenzo Mercurio Fedel, Via dello Stadio 7, 38042 Baselga di Piné (TN), Italia, P. IVA 02833120229, C.F. MRCLNZ97P29L378M. Per questioni relative ai dati personali: info@emmeeffeservices.it; per assistenza all’area clienti meteo: elaborazione@emmeeffeservices.it. Questa informativa ai sensi degli artt. 13–14 del Regolamento (UE) 2016/679 (GDPR) riguarda emmeeffeservices.it, inclusa la sezione /meteo, e si applica insieme al D.lgs. 196/2003 come modificato dal D.lgs. 101/2018.</p>
    <h2>2. Dati, finalità e basi giuridiche</h2><ul>
      <li><strong>Navigazione e sicurezza:</strong> indirizzo IP, dati tecnici di browser/dispositivo, richieste e log necessari a fornire il sito e prevenire abusi. Base: legittimo interesse alla sicurezza e al funzionamento del servizio (art. 6.1.f), bilanciato con i diritti degli utenti; cookie tecnici secondo art. 122 del Codice Privacy.</li>
      <li><strong>Account e consulenze:</strong> nome, email, password memorizzata come hash, progetto, descrizione, richieste di consulenza, stazioni associate, token e verifiche email. Base: esecuzione del servizio richiesto e misure precontrattuali (art. 6.1.b). Le email di verifica sono comunicazioni operative, non marketing.</li>
      <li><strong>Profilo pubblico:</strong> nome del proprietario, nome e descrizione progetto, tipo progetto e logo delle stazioni associate vengono mostrati nel servizio pubblico meteo. La pubblicazione fa parte del servizio richiesto per le stazioni associate (art. 6.1.b). Non inserire dati riservati, dati di altre persone senza titolo o categorie particolari di dati. Nome ed email di accesso non coincidono necessariamente: l’email, la password e i token non sono esposti nei profili pubblici.</li>
      <li><strong>Indicizzazione opzionale:</strong> la richiesta di rendere indicizzabile il profilo pubblico è facoltativa e basata sul consenso (art. 6.1.a), revocabile nelle impostazioni. Disattivare l’indicizzazione non rende il profilo privato; copie e risultati già acquisiti dai motori potrebbero richiedere tempo o una richiesta al motore per essere rimossi. Nascondere una stazione dalla mappa non blocca l’accesso tramite URL diretto.</li>
      <li><strong>Contatti e obblighi:</strong> dati forniti via email/telefono per rispondere, gestire servizi e adempiere obblighi di legge (art. 6.1.b e c); eventuale tutela di diritti (art. 6.1.f). Nessun invio promozionale è attivato dal sito.</li>
    </ul>
    <h2>3. Conferimento e modalità</h2><p>Nome, email, password e presa visione dell’informativa e delle condizioni sono necessari alla registrazione; gli altri campi del progetto sono facoltativi. Senza i dati necessari non è possibile creare o verificare l’account. I trattamenti avvengono con strumenti informatici e accessi autorizzati. Non svolgiamo decisioni automatizzate con effetti giuridici né profilazione pubblicitaria.</p>
    <h2>4. Destinatari e servizi esterni</h2><p>Utilizziamo Vercel per hosting e, quando configurato, Vercel Blob per loghi pubblici; AlterVista per database clienti, API meteo e invio delle email operative. I dati possono essere trattati da personale autorizzato e fornitori tecnici nei rispettivi ruoli e, quando dovuto, da autorità competenti. Le mappe richiedono immagini ai server OpenStreetMap, ai quali il browser comunica IP e dati tecnici; loghi e immagini esterne possono comportare richieste al relativo hosting. I link a siti terzi hanno informative proprie. I font del sito sono distribuiti dal sito, senza richieste del browser a Google Fonts.</p><p>Per informazioni sui fornitori: <a href="https://vercel.com/legal/privacy-policy">Vercel</a>, <a href="https://www.altervista.org/privacy.php">AlterVista</a>, <a href="https://osmfoundation.org/wiki/Privacy_Policy">OpenStreetMap Foundation</a>. La lista dei fornitori e le garanzie applicabili sono disponibili richiedendole al Titolare.</p>
    <h2>5. Trasferimenti internazionali</h2><p>I servizi cloud possono comportare trattamenti fuori dallo Spazio economico europeo. Gli eventuali trasferimenti devono avvenire con decisioni di adeguatezza applicabili o garanzie previste dagli artt. 44–49 GDPR, quali clausole contrattuali standard e misure supplementari quando necessarie. Puoi richiedere al Titolare dettagli sulle destinazioni e copia delle garanzie applicabili.</p>
    <h2>6. Conservazione</h2><p>I dati del profilo sono conservati per la durata dell’account. Alla cancellazione vengono eliminati profilo, sessioni, richieste e token di verifica dal database operativo; le misurazioni meteo sono conservate senza associazione all’account eliminato. Le sessioni hanno validità di 8 ore, i link di verifica 24 ore e i contatori antiabuso una finestra di 15 minuti; record scaduti possono restare nell’archivio tecnico fino alla pulizia. Loghi pubblici, copie tecniche e backup richiedono rimozione e rotazione anche presso lo storage: per richiederla contatta il Titolare. Corrispondenza e documenti sono conservati per il tempo necessario a gestire la richiesta o il rapporto e, se applicabili, per gli obblighi fiscali e di tutela dei diritti. I log seguono i tempi di conservazione del servizio hosting e le necessità documentate di sicurezza.</p>
    <h2>7. Diritti</h2><p>Puoi chiedere accesso, rettifica, cancellazione, limitazione e, nei casi previsti, portabilità; opporti ai trattamenti basati sul legittimo interesse e revocare il consenso senza pregiudicare i trattamenti precedenti (artt. 15–22 GDPR). Scrivi a info@emmeeffeservices.it. Rispondiamo di norma entro un mese, con eventuale proroga motivata nei casi previsti dall’art. 12 GDPR. Puoi presentare reclamo al <a href="https://www.garanteprivacy.it">Garante per la protezione dei dati personali</a> o all’autorità competente e ricorrere all’autorità giudiziaria.</p>
    <h2>8. Aggiornamenti</h2><p>Questa informativa riguarda la configurazione attuale del sito. Modifiche ai servizi o alle finalità saranno riportate qui e, quando richiesto, comunicate agli interessati prima di avviare nuovi trattamenti.</p>
  </LegalPage>;
}
